DEEPSORT:
  # REID_CKPT: "./deep_sort/deep/checkpoint/ckpt.t7"
  REID_CKPT: "/workspace/models/deep_sort_pytorch/last.t7"
  MAX_DIST: 0.2
  MIN_CONFIDENCE: 0.3
  NMS_MAX_OVERLAP: 0.5
  MAX_IOU_DISTANCE: 0.7
  MAX_AGE: 70
  N_INIT: 3
  NN_BUDGET: 100
  TRACK_CLASS: -1 # -1, 所有类别  
                  # yolov3, person_id = 0; car_id = 2,  选择人cls_ids=0，作为跟踪; car, cls_ids=2, 具体见 coco.name; 
  